module ExceptionPos;

exception Exception1;

exception Exception2(Int, List<Bool>);

{
  Exception e1 = Exception1;
  Exception e2 = Exception2(3,list[True,False]);
  Exception e3 = e1;

  // Bool catched1 = False;
  // Bool catched2 = False;

  try {
      throw e2;
      throw Exception1;
      throw e1;
  }
  catch {
      Exception1 => println(toString(False)); // catched1 = True;
      Exception2(4,z) => println(toString(False));
      Exception2(x,y) => skip;
      _ => skip;
  }
  // assert (catched1 == True);
  try {
      throw e2;
      throw e1;
  }
  catch {
      Exception1 => skip;
      Exception2(x,z) => println(toString(True)); // catched2 = True;
      _ => skip;
  }
  finally {
      println(toString(True));
  }

  Int x = 0;
}